// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:05ba5cd9-a098-4533-9f11-5bf806b522cd",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_IZY3taDaW",
    "aws_user_pools_web_client_id": "1onnmq6r1na3tja1iuod2tdac2"
};


export default awsmobile;
